language: python
python:
 - "2.7"
install:
 - sudo apt-get install python-dev
 - pip install --upgrade pip 
 - pip install -r requirements/local.txt
script:
 - python src/manage.py test apps.home --settings=ValoracionEmpresas.settings.local
